### ISSUE TITLE
Speed up CLI startup

### ISSUE THREAD

**Issue by ZeroIntensity** [ZeroIntensity/view.py#106]
### Improvement Description

The CLI takes a second or so to initialize. Moving the imports around should hopefully fix this. 

### Improvement Request Example API

N/A

**Comment by raptor-07** [comment]
Can I get some more info? Imports in what files?

The idea that reordering imports can help with speed has never crossed my thoughts!?

**Comment by ZeroIntensity** [comment]
Well, the CLI (found in `src/view/__main__.py`) takes a second or so to fully initialize. I'm guessing this is due to Python taking some time to import everything (at least that's what's been the problem in the past).

Maybe delaying imports until they are needed in the CLI will speed it up

**Comment by Madhusri02** [comment]
I guess it takes some time to load just because of the importing of modules and using of asynchronous operations which blocks the synchronous operations..

**Comment by ZeroIntensity** [comment]
Something else is slowing it down, not sure what.
