### ISSUE TITLE
Custom Loaders

### ISSUE THREAD

**Issue by ZeroIntensity** [ZeroIntensity/view.py#107]
### Feature description

For "batteries-detachable" purposes, there should be an API for creating custom loaders. Perhaps some plugin API could be introduced with this? (If so, that will be a separate issue).

### Feature example API

```toml
[app]
loader = "custom"
```

```py
from view import new_app, App, Route
from pathlib import Path

@app.loader
async def load(app: App, path: Path) -> list[Route]:
    return [...]
```

**Comment by tallhypnosis** [comment]
could you please elaborate more on this required feature ?
