### ISSUE TITLE
View CLI Project Creation throws error

### ISSUE THREAD

**Issue by pravintargaryen** [ZeroIntensity/view.py#131]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have Followed the view.py installation instructions from https://view.zintensity.dev/getting-started/installation/ and the installation worked correctly. However project/app creation via View CLI throws 'File Not Found error' 
![1](https://github.com/ZeroIntensity/view.py/assets/96950453/d72a416b-753a-4874-92a3-98fc7c0caf46)

(venv) PS E:\2024\day_24> python -m view init
Project name [my_app]: new_app
Loader strategy (manual, filesystem, simple) [simple]: simple
Create repository? [Y/n]: Y
Create virtual environment? [Y/n]: Y
 
Created new_app
Initializing repository...
Initialized empty Git repository in E:/2024/day_24/new_app/.git/
 
Creating venv...
Created virtual environment in new_app.venv
Installing view.py...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "E:\2024\day_24\venv\Lib\site-packages\view__main.py", line 365, in <module>
    main()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\2024\day_24\venv\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "E:\2024\day_24\venv\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\2024\day_24\venv\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\2024\day_24\venv\Lib\site-packages\click\core.py", line 783, in invoke
    return callback(args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\2024\day_24\venv\Lib\site-packages\view__main__.py", line 285, in init
    res = subprocess.call(
          ^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\subprocess.py", line 389, in call
    with Popen(popenargs, **kwargs) as p:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified

### Expected Behavior

Installation of new View.py app with necessary starter files

### Steps To Reproduce

1. Follow the Installation instructions of View.py as described in https://view.zintensity.dev/getting-started/installation/
2. Once installed, proceed to Project Creation via View CLI https://view.zintensity.dev/getting-started/creating_a_project/
3. Observe the Terminal for Error message 

### Anything else

OS : Windows 10 Pro for Workstations
Python: CPython Version 3.11

**Comment by ZeroIntensity** [comment]
Unable to reproduce on Linux, CPython 3.11 with view.py alpha 8

**Comment by pravintargaryen** [comment]
@ZeroIntensity you can close this issue
