### ISSUE TITLE
Fix MkDocs Search

### ISSUE THREAD

**Issue by ZeroIntensity** [ZeroIntensity/view.py#150]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If you use the "Search documentation" feature on the docs, some of the results will appear as HTML elements (i.e. their title is `<code>...`).

### Expected Behavior

It should instead display just a title (or not display it all).

### Steps To Reproduce

Search `"hello"` on the docs, for example.

### Anything else

This is likely due to `mkdocstrings` messing with TOC and the search displaying it with the extra `mkdocstrings` tag. If anyone is more experienced with MkDocs themes or `mkdocstrings`, feel free to work on this.

**Comment by pawamoy** [comment]
Relevant PR: https://github.com/mkdocs/mkdocs/pull/3560.

**Comment by ZeroIntensity** [comment]
This is no longer relevant as of the switch to `mkdocs-material`
