### ISSUE TITLE
Migrate test suite to Pytest

### ISSUE THREAD

**Issue by ZeroIntensity** [ZeroIntensity/view.py#164]
### Description:

Ward has been great, but using it over Pytest makes #109 more or less impossible. Pytest and Ward are pretty similar, but most developers are familiar with Pytest anyway, so this change will probably be for the best.

**Comment by tallhypnosis** [comment]
I could work on this, if you want me to ?

**Comment by ZeroIntensity** [comment]
That would be great! Most of this issue will just be adding `pytest.mark.asyncio` and renaming the functions. 

If you need to me to set up the changes to the actions workflow, I can do that for you. Nobody likes messing with workflow files.

**Comment by tallhypnosis** [comment]
sure

**Comment by ZeroIntensity** [comment]
Any progress here?

**Comment by tallhypnosis** [comment]
done with the changes

**Comment by ZeroIntensity** [comment]
Great! Go ahead and make a PR, I'll update the workflows if you haven't already

**Comment by tallhypnosis** [comment]
before i make the PR is there anything to mind or any suggestion ?

**Comment by tallhypnosis** [comment]
Do you want  me to change something in the readme or any doc file ?

**Comment by ZeroIntensity** [comment]
Nope, I got it.
