### ISSUE TITLE
Dead code removal

### ISSUE THREAD

**Issue by ZeroIntensity** [ZeroIntensity/view.py#21]
When #8 is done (or even before), [src/view/nodes.py](https://github.com/ZeroIntensity/view.py/blob/master/src/view/nodes.py) could get removed, and the JSX syntax should switch over to using the components.

**Comment by JanaganSaravanan** [comment]
Hi! is this issue open? if yes, I would like to work on this?.

**Comment by ZeroIntensity** [comment]
Yup. Go ahead.

**Comment by ZeroIntensity** [comment]
Will be done when JSX gets finished
