### ISSUE TITLE
Improve docs design

### ISSUE THREAD

**Issue by ZeroIntensity** [ZeroIntensity/view.py#26]
I suck at web design. Anything is probably better than the hunk of junk on the docs site right now.

**Comment by ZeroIntensity** [comment]
I'm actually about to do some changes to docs, I'll give you details when it's ready.

**Comment by JanaganSaravanan** [comment]
I got it. Thank you for your quick reply.

**Comment by ZeroIntensity** [comment]
#68 just got merged, so you are now free to work on this. Basically, I don't really care what you do in terms of redesigning the docs, just make it look better than it already is. If you want to completely redesign it, go for it. We use [mkdocs](https://mkdocs.org) for documentation, so you can take a look at [their docs](https://www.mkdocs.org/dev-guide/themes/) on designing themes. 

It needs to contain the following attributes:
- Look catchy enough to be used for documentation
- Responsive (i.e. it works correctly on all devices)
- Uses the view.py color theme (mint greenish, basically just the colors in the logo)

If you have any questions or want feedback, you can run it by in [our discord](https://discord.gg/tZAfuWAbm2).

**Comment by ZeroIntensity** [comment]
Also, we use [tailwind](https://tailwindcss.com) for CSS as of now. If you don't want to use it, that's fine, just make sure it works with the attributes above. If you do want to use tailwind, then the workflow goes like this:

In one terminal, you run `mkdocs serve` in the top level view.py directory.
Then, in another terminal, `cd` into `html` and run `yarn watch`. This will start the Tailwind build process.

Note that you do have to restart `mkdocs serve` every time you make a change to the HTML.

**Comment by ZeroIntensity** [comment]
Removing assignee for inactivity.

**Comment by ZeroIntensity** [comment]
Closed in favor of #78
