### ISSUE TITLE
Issue templates

### ISSUE THREAD

**Issue by ZeroIntensity** [ZeroIntensity/view.py#27]
yeah

**Comment by RP99** [comment]
Hi @ZeroIntensity,

If this is still open, I would like to contribute. Can you provide specifics for creating Issue Templates.

**Comment by ZeroIntensity** [comment]
Sure. We need three types of issue templates:
- Feature/improvement requests
- Bug reports
- Questions

Feature/improvement requests should contain a section asking for a description describing what the request is and a section containing an example API for the feature. For example, a request for adding `foo` to `view.bar` could look like:

**Description:** This adds support for `foo` to `bar`

**Example API:**
```py
view.bar.foo(...)
```

Next, I don't really know if this is possible with issue templates, but ideally, there should be some checkbox or button that adds the `improvement` or `feature` label depending on what the user added. The `request` label should also be added.

Assuming the checkbox/button thing from above is possible for bug reports, we want a way to differentiate crashes (e.g. segmentation faults) from bugs (incorrect behavior, error thrown, etc.). Then, provide a section for the full traceback/console output.

Finally, for questions, not much is needed just make sure to have some sort of thing saying "have you asked in our discord server"

**Comment by RP99** [comment]
@ZeroIntensity check this  ~ [Question template form](https://github.com/RP99/view.py_RP99/blob/master/.github/ISSUE_TEMPLATE/Question.yml) and let me know if this ok or whether I need to make any changes before committing to main.

**Comment by RP99** [comment]
> Next, I don't really know if this is possible with issue templates, but ideally, there should be some checkbox or button that adds the improvement or feature label depending on what the user added. The request label should also be added. 
> Assuming the checkbox/button thing from above is possible for bug reports, we want a way to differentiate crashes (e.g. segmentation faults) from bugs (incorrect behavior, error thrown, etc.). Then, provide a section for the full traceback/console output.

@ZeroIntensity   Also, above dynamic issue templates creation requirement can't be created and is giving unexpected results. So, should I create separate issue templates say Bug_Report and Crash_Report?

**Comment by ZeroIntensity** [comment]
Go for it.

**Comment by RP99** [comment]
> Go for it.

This is in regards to:
First Comment ??
> @ZeroIntensity check this ~ [Question template form](https://github.com/RP99/view.py_RP99/blob/master/.github/ISSUE_TEMPLATE/Question.yml) and let me know if this ok or whether I need to make any changes before committing to main.

**OR** 

Second Comment??
> > Next, I don't really know if this is possible with issue templates, but ideally, there should be some checkbox or button that adds the improvement or feature label depending on what the user added. The request label should also be added.
> > Assuming the checkbox/button thing from above is possible for bug reports, we want a way to differentiate crashes (e.g. segmentation faults) from bugs (incorrect behavior, error thrown, etc.). Then, provide a section for the full traceback/console output.
> 
> @ZeroIntensity Also, above dynamic issue templates creation requirement can't be created and is giving unexpected results. So, should I create separate issue templates say Bug_Report and Crash_Report?

**Comment by ZeroIntensity** [comment]
Oh, I didn't see the first one, my bad. I was talking about the second one. For the first one, it looks great.

**Comment by RP99** [comment]
> > Next, I don't really know if this is possible with issue templates, but ideally, there should be some checkbox or button that adds the improvement or feature label depending on what the user added. The request label should also be added.
> > Assuming the checkbox/button thing from above is possible for bug reports, we want a way to differentiate crashes (e.g. segmentation faults) from bugs (incorrect behavior, error thrown, etc.). Then, provide a section for the full traceback/console output.
> 
> @ZeroIntensity Also, above dynamic issue templates creation requirement can't be created and is giving unexpected results. So, should I create separate issue templates say Bug_Report and Crash_Report?

So, I have created separated templates. But, there seems to be no label for crash. Hence, I had to create a new label as _crash_

**Comment by ZeroIntensity** [comment]
Huh? There is a crash label, see #38

**Comment by RP99** [comment]
Oh! I can see only 10 labels (no crash present) in forked project as opposed to 17 in main. How do I sync it?

**Comment by ZeroIntensity** [comment]
Not sure, I can always fix it before it gets merged

**Comment by RP99** [comment]
Ok. I will retry by forking the project.

**Comment by RP99** [comment]
I will work on Feature and Bug Request issue template forms tomorrow (separate like Bug and Crash reports). Signing off for now.
