### ISSUE TITLE
Add docstrings to public functions

### ISSUE THREAD

**Issue by ZeroIntensity** [ZeroIntensity/view.py#29]
Should follow the Google style. Will add `mkdocstrings` when ready.

**Comment by 459-ferd** [comment]
Hello @ZeroIntensity, I am a beginner to open-source contributions and I would like to contribute. Where do I start?

**Comment by ZeroIntensity** [comment]
No problem, if you need I can walk you through the codebase in [our discord](https://discord.gg/tZAfuWAbm2). Do you know the basics of how Git and GitHub work?

**Comment by 459-ferd** [comment]
Yes. I understand forking and cloning repos. I think I am 7 out of 10 on understanding the two platforms.

**Comment by ZeroIntensity** [comment]
This is more or less finished.
