### ISSUE TITLE
[BUG] : Getting build warning in when compiling css using tailwind

### ISSUE THREAD

**Issue by md-abid-hussain** [ZeroIntensity/view.py#47]
I'm getting following warning:

![Screenshot (8)](https://github.com/ZeroIntensity/view.py/assets/101964499/e7dbbdd9-f530-4c2f-87dc-050a366ac514)

Above warning is because the tailwind is looking for .html and .js extension file in node_module folder as well. This also slow down the build process.

`content: ["./**/*.{html,js}"]`

I would like to work on this issue as well and fixing this might fix the #41

**Comment by ZeroIntensity** [comment]
I think #41 is unrelated, I'm pretty sure that's a netlify thing

**Comment by md-abid-hussain** [comment]
Yeah it is unrelated to that issue but I've found the solution
