### ISSUE TITLE
Docs Overhaul

### ISSUE THREAD

**Issue by ZeroIntensity** [ZeroIntensity/view.py#78]
### Feature description

Complete rewrite of the docs, including both the markdown and `mkdocs` theme. Should hopefully look something like [NextJS](https://nextjs.org) or [Tailwind](https://tailwindcss.com/) when done.

### Feature example API

N/A

**Comment by muresan-gabriel** [comment]
Hello! I'm new to GitHub contributions. Found this Open Issue and I'd like to give it a try. Never really worked with mkdocs, but I'll have an in-depth look at how the docs currently work and provide a solution to this Open Issue. I see it still uses CSS, so it seems to be fine by me.

Do you require Figma prototypes before development or could I jump straight to styling?

Thank you in advance!

**Comment by ZeroIntensity** [comment]
I don't use Figma, so you can jump right in. If you need any help with MkDocs, they have a [good documentation](https://www.mkdocs.org/dev-guide/themes/) on designing themes. This is a big issue, so I'll work on it alongside you. Be sure to join [the discord](https://discord.gg/tZAfuWAbm2) if you have any questions.

**Comment by ZeroIntensity** [comment]
I think it might be possible to build the docs in Next, would that be helpful if I set that up?

**Comment by muresan-gabriel** [comment]
Sure thing! Thanks a lot! Whichever you think would better fit your preferences. I can get into the MkDocs documentation without an issue, but I can jump into Next as well. Whatever works for you.

**Comment by ZeroIntensity** [comment]
I think let's stick with MkDocs for now, since it's really easy to write documentation for it. If you want to use Next, be sure to let me know.

**Comment by muresan-gabriel** [comment]
No worries, bud! 

Having that already set up is great and I'd rather accomodate myself around what you have, than force you to use something else. 

Cheers, I'll keep you posted on Discord with the progress.

**Comment by ZeroIntensity** [comment]
[Vue](https://vuejs.org/) and [Nuxt](https://nuxt.com/) are also both good examples of how this could turn out.

**Comment by hasansezertasan** [comment]
I highly encourage you people to stick to the MkDocs, it's great and it's python 😎
